
title: GuanLinWu
#logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: false
theme: jekyll-theme-slate
github name: GuamLinWu
linkedin: https://www.linkedin.com/in/%E5%86%A0%E9%9C%96-%E5%90%B3-ab3760346/
